### ISSUE TITLE
Understand the connection between causal impact implementations

### ISSUE THREAD

**Issue by FTamas77** [google/tfp-causalimpact#34]
On the README.md the link is broken:

>  https://github.com/dafiti/causalimpact developed at Dafiti by Willian Fuks. 
Or better to say, there is no such repo.

I know Google's R implementation of the causal impact. This package is based on it.
I also tried this package: https://github.com/jamalsenouci/causalimpact, a portion of the R implementation.

My questions:
* What happened with the https://github.com/dafiti/causalimpact here?
* What is the difference between this package and https://github.com/jamalsenouci/causalimpact?

I'm new to time-series causal analysis, so, it is a challenge to understand it, so I want to start with the best package.

**Comment by leogabrielp** [comment]
Hello! @FTamas77 
I faced the same doubts and after digging a bit I found that the original repository that you mention has been deleted some years ago. 
William Fucks, one of the developers of the library recreated it again, this time by using some new implementations in Tensorflow. You can find the new repository here:
https://github.com/WillianFuks/tfcausalimpact

And some comments about this topic:
https://github.com/WillianFuks/tfcausalimpact/issues/22

Hope you find it useful. All best!

**Comment by FTamas77** [comment]
Thanks.

Now, there are two similar libraries:
https://github.com/WillianFuks/tfcausalimpact
https://github.com/google/tfp-causalimpact

I read the linked talking and the first one is much closer to the R lib. I will use both and compare them.

There is no more such a big causalimpact library, so, this is solved.

**Comment by ColCarroll** [comment]
For what it is worth, this library faithfully reproduces the inference methods currently used in the R library (and described in the paper). The library @WillianFuks implemented is very nice, and I have not dived too deeply into how closely the models match up with the models from the paper, but I would be surprised if it used the exact gibbs samplers used here (and in R)!
