### ISSUE TITLE
package folder holds same name as tfcausalimpact therefore impossible to co-exist in the same environment

### ISSUE THREAD

**Issue by Yazmaz98** [google/tfp-causalimpact#37]
Hi, it has come upon my attention that your library and [WillianFuks's ](https://github.com/WillianFuks/tfcausalimpact) both have the folder causalimpact when we install them. I needed to install both on the same poetry environment to be able to run either models as I want and compare but was not directly able to as the second one overwrites the first one's previously installed folder "causalimpact". Is there any way that this could be solved please ? Thanks !

**Comment by ColCarroll** [comment]
There's not an easy way to solve this, sorry! import names are not guaranteed to be unique. The best you could do is to manually update the installed code to have a new name, but that might be hard!
